CELL_SIZE = 20
NUM_OF_ROWS = 25
NUM_OF_COLS = 50
WINDOW_HEIGHT = 500
WINDOW_WIDTH = 1000
LANDMINE_WIDTH = 3 * CELL_SIZE
LANDMINE_HEIGHT = CELL_SIZE
SOLDIER_WIDTH = 2 * CELL_SIZE
SOLDIER_HEIGHT = 4 * CELL_SIZE
KNIGHT_ROW = 4
KNIGHT_COL = 2

FIELD_BACKGROUND_COLOR = (200, 250, 100)
UNDERGROUND_BACKGROUND_COLOR = (0, 0, 0)
UNDERGROUND_GRID_COLOR = (102, 255, 0)

GRASS = "grass.png"
LANDMINE_IMAGE = 'mine.png'
SOLDIER = 'soldier.png'
UNDERGROUND_SOLDIER = 'soldier_night.png'
EXPLOSION = 'explotion.png'
INJURED_SOLDIER = 'injury.png'
FLAG_IMAGE = 'flag.png'

EMPTY = 0
BUSH = 0
LANDMINE = 1
FLAG = 2

NUM_OF_LANDMINES = 20